In [1]:
import numpy as np
import pandas as pd

In [15]:
num = np.arange(1,11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
reshape = num.reshape(2,5)
reshape
print(reshape)
print('Shape of this matrix is:',reshape.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape of this matrix is: (2, 5)


In [25]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a1 = np.arange(5,16)
a1
print('The elements between 5 and 15 is:',a1)

The elements between 5 and 15 is: [ 5  6  7  8  9 10 11 12 13 14 15]


In [155]:
j = {'Apple':3,'Bananas':2,'Orange':1}
series = pd.Series(data=j)
series

Apple      3
Bananas    2
Orange     1
dtype: int64

In [151]:
j = {'Apple': 3, 'Bananas': 2, 'Orange': 1}
j['Pears'] = 4
series = pd.Series(data=j)
print(series)


Apple      3
Bananas    2
Orange     1
Pears      4
dtype: int64


In [163]:
data = {'Name':['Alice','Bob','Charlie','Reghu','Keshu','Ammu','Papu','Manju','Anju','Abhi'],
        'Age':[20,25,35,18,22,21,30,32,17,25],
        'Gender':['F','M','M','M','M','F','M','F','F','M']}
data

{'Name': ['Alice',
  'Bob',
  'Charlie',
  'Reghu',
  'Keshu',
  'Ammu',
  'Papu',
  'Manju',
  'Anju',
  'Abhi'],
 'Age': [20, 25, 35, 18, 22, 21, 30, 32, 17, 25],
 'Gender': ['F', 'M', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M']}

In [167]:
type(data)

dict

In [169]:
details = pd.DataFrame(data)
details

Name  Age Gender
0    Alice   20      F
1      Bob   25      M
2  Charlie   35      M
3    Reghu   18      M
4    Keshu   22      M
5     Ammu   21      F
6     Papu   30      M
7    Manju   32      F
8     Anju   17      F
9     Abhi   25      M

In [173]:
details['Occupation'] =['Programmer','Manager','Analyst','Manager','Programmer','Programmer','Programmer','Analyst','Analyst','Analyst']
details

Name  Age Gender  Occupation
0    Alice   20      F  Programmer
1      Bob   25      M     Manager
2  Charlie   35      M     Analyst
3    Reghu   18      M     Manager
4    Keshu   22      M  Programmer
5     Ammu   21      F  Programmer
6     Papu   30      M  Programmer
7    Manju   32      F     Analyst
8     Anju   17      F     Analyst
9     Abhi   25      M     Analyst

In [175]:
new_details = details[details['Age']>=30]
new_details

Name  Age Gender  Occupation
2  Charlie   35      M     Analyst
6     Papu   30      M  Programmer
7    Manju   32      F     Analyst

In [179]:
new_details.to_csv('Company_details.csv',index =False)


In [183]:
with open('company_details.csv','r')as detail1:
    content =detail1.read()
    print(content)

Name,Age,Gender,Occupation
Charlie,35,M,Analyst
Papu,30,M,Programmer
Manju,32,F,Analyst

